site_name: Model Insertion Checker (MIC)
nav:
  - Home: index.md
  - Usage: usage.md
theme: 
  name: material
  logo: 'logo.png'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
