site_name: Model Insertion Checker (MIC)
nav:
  - Home: index.md
  - Available commands: usage.md
  - Configure: configure.md
  - Add model: usage-add-model.md
  - 'Add modelconfiguration':
      - 'Before you start...': 'model_configuration/02-pre-steps.md'
      - 'Getting started': 'model_configuration/03-create-skeleton.md'
      - 'Copy your data': 'model_configuration/04-copy-your-data.md'
      - 'Write the invocation lines': 'model_configuration/05-write-invocation.md'
      - 'Pass the parameters': 'model_configuration/06-pass-parameters.md'
      - 'Run and Validate': 'model_configuration/07-validate.md'
      - 'Identify the outputs': 'model_configuration/08-outputs.md'
      - 'Publish': 'model_configuration/09-publish.md'
  - FAQ: faq.md
  - Glossary: glossary.md

theme: 
  name: material
  logo: 'logo.png'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
